set nocompatible
syntax on

" =============== Vundle Initialization ===============
" This loads all the plugins specified in ~/.vim/vundle.vim
" Use Vundle plugin to manage all other plugins
if filereadable(expand("~/.vim/vundles.vim"))
    source ~/.vim/vundles.vim
endif

filetype on
filetype plugin on
filetype indent on

" =============== Indentation =========================
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent

" =============== General config ======================
set nobackup
set noswapfile
set nowritebackup

set backupdir=~/.vim/backup
set directory=~/.vim/tmp
set undodir=~/.vim/backups
set undofile

" by derekwyatt
set stl=%f\ %m\ %r%{fugitive#statusline()}\ Line:%l/%L[%p%%]\ Col:%v\ Buf:#%n\ [%b][0x%B]

set conceallevel=2
set diffopt+=context:3
set noerrorbells visualbell t_vb=  " Disable bells
set formatoptions=crqwnl1          " Help fo-table
set hidden             " Change buffer - without saving
set history=100        " Number of things to remember in history.
set hlsearch
set incsearch
set ignorecase         " Case insensitive search
set smartcase          " Non-case sensitive search
set laststatus=2       " Always show the statusline
set cmdheight=1
set relativenumber
set report=0
set scrolloff=6       " minimum lines to keep above and below cursor
set scrolljump=10
set shortmess=atToOI
set showcmd		" show incomplete cmds
set showmode		" show current mode
set nowrap             " Line wrapping off
set splitbelow
set splitright

" Ubuntu에서 에러 발생함
set fillchars=vert:│,fold:┄,diff:╱
"set listchars=tab:│\ ,trail:⌴,eol:·,precedes:◂,extends:▸
set showbreak=↪

set nolist
set lazyredraw
set autoread           " Automatically reload changes if detected
set autowrite          " Writes on make/shell commands
set cf                 " Enable error files & error jumping.
set clipboard+=unnamed " Yanks go on clipboard instead.

" 2014.1.10 all 한번 사용해보자 
set virtualedit=onemore

set backspace=2        " Delete everything with backspace
set showmatch          " Show matching brackets.
set matchtime=2        " How many tenths of a second to blink

" current buffer, buffers in window, other loaded buffers, tags
set complete=.,w,b,t

" When completing by tag, show the whole tag, not just the function name
set showfulltag

set timeoutlen=300   " Mapping delay
set ttimeoutlen=-1   " Key code delay

let Tlist_Ctags_Cmd='/usr/local/bin/ctags'

" 성능. 200자 넘는 라인은 syntax highlight 하지 않는다.
set synmaxcol=200


" =============== Mouse ===============================
set mousehide   " Hide mouse after chars typed
set mouse=a     " Mouse in all modes

" =============== Auto completion =====================
set wildmenu                            " show list instead of just completing
set wildmode=list:longest,list:full     " command <Tab> completion, list matches, then longest common part, then all.
set wildignore+=.git,target,.DS_Store,.settings,*.class,dist,logs,img,*.log,*.zip,*.jpg,*.gif,*.png
set wildignore+=*/.target/*,.target,.idea,tags,*/node-modules/*

" =============== Folding =============================
set foldmethod=marker
set foldenable
set foldlevel=0
set foldcolumn=0
set foldtext=FoldText()
set foldnestmax=3
" These commands open folds
set foldopen=block,insert,jump,mark,percent,quickfix,search,tag,undo

" Source vim config files {{{
	runtime! config/plugins.vim
	runtime! config/autocommands.vim
	runtime! config/commands.vim
	runtime! config/foldtext.vim
	runtime! config/make.vim
	runtime! config/mappings.vim
	runtime! config/gui.vim
	runtime! config/terminal.vim
	runtime! config/highlight.vim
" }}}

if filereadable("~/.vimrc.local")
    source ~/.vimrc.local
endif

" Source extra config files {{{
	" Parse local vimrc (useful for per-project settings)
	if filereadable(".lvimrc")
		source .lvimrc
	endif
" }}}
